version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bisbis10
      POSTGRES_PASSWORD: bisbis10
      POSTGRES_DB: bisbis10
    volumes:
      - type: bind
        source: ~/Downloads/AT&T/data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
